import { Feather } from "@expo/vector-icons";
import { useQuery } from "@tanstack/react-query";
import * as Clipboard from "expo-clipboard";
import * as Haptics from "expo-haptics";
import * as Linking from "expo-linking";
import React, { useState } from "react";
import {
  Alert,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useLocation } from "@/context/LocationContext";
import { fetchNearbySpecies } from "@/services/iNaturalist";
import { withCache } from "@/services/cache";
import { getEcosystemRoles, getRoleLabel, buildImpactChain } from "@/services/ecologyModel";
import { useColors } from "@/hooks/useColors";

type ReportType = "consumer" | "policy";

const STAKEHOLDERS = [
  {
    id: "city-council",
    name: "City Council",
    role: "Elected Official",
    org: "City Council",
    category: "Government",
    email: "council@yourcity.gov",
    website: "https://yourcity.gov/council",
    icon: "users",
    color: "#60A5FA",
  },
  {
    id: "parks",
    name: "Parks Department",
    role: "Director",
    org: "Parks & Recreation",
    category: "Government",
    email: "parks@yourcity.gov",
    website: "https://yourcity.gov/parks",
    icon: "map",
    color: "#4ADE80",
  },
  {
    id: "newspaper",
    name: "Local Newspaper",
    role: "Environment Reporter",
    org: "Local News",
    category: "Media",
    email: "environment@localnews.com",
    website: "https://localnews.com",
    icon: "file-text",
    color: "#FBBF24",
  },
  {
    id: "nonprofit",
    name: "Environmental Nonprofit",
    role: "Conservation Director",
    org: "Local Conservation Group",
    category: "Nonprofit",
    email: "info@localconservation.org",
    website: "https://localconservation.org",
    icon: "heart",
    color: "#A78BFA",
  },
];

function generateReport(
  type: ReportType,
  city: string,
  radius: number,
  speciesName: string,
  scientificName: string,
  role: string,
  observationCount: number,
  chain: ReturnType<typeof buildImpactChain>
): string {
  if (type === "consumer") {
    return `📍 Biodiversity Report — ${city} (${radius}km radius)
Generated by Life Web • ${new Date().toLocaleDateString()}

SPECIES SPOTLIGHT: ${speciesName} (${scientificName})

What we found:
Community scientists have recorded ${observationCount} research-grade observations of ${speciesName} near ${city}. This species plays the role of ${role.toLowerCase()} in the local ecosystem.

Why it matters:
${chain.summary}

What could happen:
${chain.nodes.slice(1).map((n) => `• ${n.description}`).join("\n")}

What you can do:
• Report sightings to iNaturalist
• Support local habitat preservation
• Contact your parks department about habitat management
• Share this report with local conservation groups

Data caveat:
${chain.credibilityNote} All data sourced from iNaturalist community observations.

---
Powered by Life Web & iNaturalist`;
  }

  return `BIODIVERSITY IMPACT ASSESSMENT
${city} Region (${radius}km radius)
Date: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY

Community science observations from iNaturalist indicate notable biodiversity activity near ${city}. This report focuses on ${speciesName} (${scientificName}), documented in ${observationCount} research-grade observations within the study area.

SPECIES PROFILE

Common Name: ${speciesName}
Scientific Name: ${scientificName}
Ecosystem Role: ${role}
Observation Count (Research Grade): ${observationCount}
Study Radius: ${radius}km from ${city}

ECOLOGICAL SIGNIFICANCE

${chain.summary}

POTENTIAL IMPACT CHAIN

${chain.nodes.map((n, i) => `${i + 1}. ${n.label}: ${n.description}`).join("\n")}

DATA METHODOLOGY

All observations sourced from iNaturalist (inaturalist.org) using research-grade quality filter. Data normalized against total observation effort. Seasonal and observer bias are acknowledged limitations.

IMPORTANT CAVEATS

${chain.credibilityNote} Community science data reflects observer effort and accessibility of habitats, not absolute species distribution. This report should be considered alongside formal ecological assessments before policy decisions are made.

RECOMMENDED LOCAL ACTIONS

1. Commission a formal species survey to validate community observations
2. Review habitat management plans for areas with high observation density
3. Engage local naturalist groups in ongoing monitoring
4. Consider wildlife corridor protections where relevant
5. Support citizen science programs that expand observation coverage

DATA SOURCE

iNaturalist (https://www.inaturalist.org)
Powered by Life Web biodiversity app

---
This report was generated using community science data and simplified ecological models. It is intended to inform and educate, not to serve as a definitive scientific or legal document.`;
}

export default function ReportsScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const { lat, lng, radius, cityName } = useLocation();

  const [reportType, setReportType] = useState<ReportType>("consumer");
  const [generatedReport, setGeneratedReport] = useState<string | null>(null);
  const [selectedStakeholder, setSelectedStakeholder] = useState<string | null>(null);
  const [editableEmail, setEditableEmail] = useState("");

  const { data: species } = useQuery({
    queryKey: ["nearby-species", lat, lng, radius],
    queryFn: () =>
      withCache(`nearby-${lat}-${lng}-${radius}`, () =>
        fetchNearbySpecies(lat!, lng!, radius, 50)
      ),
    enabled: !!lat && !!lng,
  });

  const topSpecies = species?.[0];

  function handleGenerate() {
    if (!topSpecies) return;
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    const taxon = topSpecies.taxon;
    const roles = getEcosystemRoles(taxon.iconic_taxon_name, taxon.preferred_common_name);
    const role = getRoleLabel(roles[0]);
    const chain = buildImpactChain(taxon.name, taxon.iconic_taxon_name, taxon.preferred_common_name);
    const report = generateReport(
      reportType,
      cityName || "Your Location",
      radius,
      taxon.preferred_common_name || taxon.name,
      taxon.name,
      role,
      topSpecies.count,
      chain
    );
    setGeneratedReport(report);
  }

  async function handleCopy() {
    if (!generatedReport) return;
    await Clipboard.setStringAsync(generatedReport);
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    Alert.alert("Copied!", "Report copied to clipboard.");
  }

  function handleEmail(stakeholder: (typeof STAKEHOLDERS)[0]) {
    const subject = encodeURIComponent(`Biodiversity Report — ${cityName || "Local Area"}`);
    const body = encodeURIComponent(generatedReport || editableEmail);
    Linking.openURL(`mailto:${stakeholder.email}?subject=${subject}&body=${body}`);
  }

  const topInsets = insets.top + (Platform.OS === "web" ? 67 : 0);
  const bottomInsets = insets.bottom + (Platform.OS === "web" ? 34 : 0);

  return (
    <View style={[styles.container, { backgroundColor: colors.earthDark }]}>
      <ScrollView
        contentContainerStyle={[
          styles.scroll,
          { paddingTop: topInsets + 16, paddingBottom: bottomInsets + 100 },
        ]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.title}>Civic Reports</Text>
        <Text style={[styles.subtitle, { color: "#64748B" }]}>
          Generate biodiversity reports for local leaders and media.
        </Text>

        {/* Report type selector */}
        <View style={[styles.typeSelector, { backgroundColor: "#0F1824", borderColor: "#1E293B" }]}>
          <Pressable
            onPress={() => setReportType("consumer")}
            style={[
              styles.typeTab,
              reportType === "consumer" && { backgroundColor: "#4ADE80" },
            ]}
          >
            <Text style={[styles.typeText, { color: reportType === "consumer" ? "#080C14" : "#64748B" }]}>
              Summary
            </Text>
          </Pressable>
          <Pressable
            onPress={() => setReportType("policy")}
            style={[
              styles.typeTab,
              reportType === "policy" && { backgroundColor: "#4ADE80" },
            ]}
          >
            <Text style={[styles.typeText, { color: reportType === "policy" ? "#080C14" : "#64748B" }]}>
              Policy Report
            </Text>
          </Pressable>
        </View>

        {/* Featured species */}
        {topSpecies && (
          <View style={[styles.featuredCard, { backgroundColor: "#0F1824", borderColor: "#1E293B" }]}>
            <View style={styles.featuredHeader}>
              <Feather name="star" size={14} color="#FBBF24" />
              <Text style={[styles.featuredLabel, { color: "#FBBF24" }]}>Featured Species</Text>
            </View>
            <Text style={styles.featuredName}>
              {topSpecies.taxon.preferred_common_name || topSpecies.taxon.name}
            </Text>
            <Text style={[styles.featuredSci, { color: "#64748B" }]}>{topSpecies.taxon.name}</Text>
            <Text style={[styles.featuredObs, { color: "#94A3B8" }]}>
              {topSpecies.count.toLocaleString()} nearby observations
            </Text>
          </View>
        )}

        {/* Generate button */}
        <Pressable
          onPress={handleGenerate}
          disabled={!topSpecies}
          style={({ pressed }) => [
            styles.generateBtn,
            {
              backgroundColor: topSpecies ? "#4ADE80" : "#1E293B",
              opacity: pressed ? 0.85 : 1,
            },
          ]}
        >
          <Feather name="file-text" size={18} color={topSpecies ? "#080C14" : "#475569"} />
          <Text style={[styles.generateText, { color: topSpecies ? "#080C14" : "#475569" }]}>
            Generate Report
          </Text>
        </Pressable>

        {/* Generated report */}
        {generatedReport && (
          <View style={styles.reportSection}>
            <View style={styles.reportHeader}>
              <Text style={[styles.reportLabel, { color: "#FFFFFF" }]}>Generated Report</Text>
              <Pressable onPress={handleCopy} style={[styles.copyBtn, { backgroundColor: "#0F1824" }]}>
                <Feather name="copy" size={14} color="#4ADE80" />
                <Text style={[styles.copyText, { color: "#4ADE80" }]}>Copy</Text>
              </Pressable>
            </View>
            <View style={[styles.reportBox, { backgroundColor: "#0F1824", borderColor: "#1E293B" }]}>
              <Text style={[styles.reportText, { color: "#CBD5E1" }]}>{generatedReport}</Text>
            </View>
          </View>
        )}

        {/* Outreach section */}
        <View style={styles.outreachSection}>
          <Text style={styles.outreachTitle}>Send to Local Leaders</Text>
          <Text style={[styles.outreachSubtitle, { color: "#64748B" }]}>
            Tap to open your email app with a pre-filled template. You review and send.
          </Text>

          {STAKEHOLDERS.map((s) => (
            <Pressable
              key={s.id}
              onPress={() => {
                if (!generatedReport) {
                  Alert.alert("Generate a report first", "Tap Generate Report above before sending.");
                  return;
                }
                handleEmail(s);
              }}
              style={({ pressed }) => [
                styles.stakeholderCard,
                {
                  backgroundColor: "#0F1824",
                  borderColor: "#1E293B",
                  opacity: pressed ? 0.85 : 1,
                },
              ]}
            >
              <View style={[styles.stakeholderIcon, { backgroundColor: s.color + "15" }]}>
                <Feather name={s.icon as any} size={18} color={s.color} />
              </View>
              <View style={styles.stakeholderInfo}>
                <Text style={styles.stakeholderName}>{s.name}</Text>
                <Text style={[styles.stakeholderRole, { color: "#64748B" }]}>{s.role} · {s.org}</Text>
                <Text style={[styles.stakeholderEmail, { color: s.color }]}>{s.email}</Text>
              </View>
              <View style={[styles.categoryBadge, { backgroundColor: s.color + "15" }]}>
                <Text style={[styles.categoryText, { color: s.color }]}>{s.category}</Text>
              </View>
            </Pressable>
          ))}

          <View style={[styles.placeholderNote, { backgroundColor: "#1E293B40" }]}>
            <Feather name="info" size={12} color="#475569" />
            <Text style={[styles.placeholderText, { color: "#475569" }]}>
              Stakeholder contact details are placeholders. Replace with your local representatives' actual contacts.
            </Text>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { paddingHorizontal: 20 },
  title: {
    fontSize: 26,
    fontFamily: "Inter_700Bold",
    color: "#FFFFFF",
    letterSpacing: -0.4,
  },
  subtitle: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
    marginBottom: 20,
    lineHeight: 18,
  },
  typeSelector: {
    flexDirection: "row",
    borderRadius: 14,
    borderWidth: 1,
    padding: 4,
    marginBottom: 16,
    gap: 4,
  },
  typeTab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  typeText: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
  },
  featuredCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    marginBottom: 16,
    gap: 4,
  },
  featuredHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 4,
  },
  featuredLabel: {
    fontSize: 11,
    fontFamily: "Inter_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  featuredName: {
    fontSize: 18,
    fontFamily: "Inter_700Bold",
    color: "#FFFFFF",
  },
  featuredSci: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    fontStyle: "italic",
  },
  featuredObs: {
    fontSize: 12,
    fontFamily: "Inter_500Medium",
    marginTop: 2,
  },
  generateBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 16,
    borderRadius: 16,
    marginBottom: 20,
  },
  generateText: {
    fontSize: 16,
    fontFamily: "Inter_700Bold",
  },
  reportSection: { marginBottom: 24 },
  reportHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  reportLabel: {
    fontSize: 16,
    fontFamily: "Inter_700Bold",
  },
  copyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  copyText: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  reportBox: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
  },
  reportText: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    lineHeight: 18,
  },
  outreachSection: { marginBottom: 20 },
  outreachTitle: {
    fontSize: 18,
    fontFamily: "Inter_700Bold",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  outreachSubtitle: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    lineHeight: 17,
    marginBottom: 14,
  },
  stakeholderCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 8,
    gap: 12,
  },
  stakeholderIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  stakeholderInfo: { flex: 1, gap: 2 },
  stakeholderName: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#FFFFFF",
  },
  stakeholderRole: {
    fontSize: 11,
    fontFamily: "Inter_400Regular",
  },
  stakeholderEmail: {
    fontSize: 11,
    fontFamily: "Inter_500Medium",
  },
  categoryBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  categoryText: {
    fontSize: 10,
    fontFamily: "Inter_600SemiBold",
  },
  placeholderNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    padding: 12,
    borderRadius: 12,
    marginTop: 4,
  },
  placeholderText: {
    flex: 1,
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    lineHeight: 16,
  },
});
