import { Feather } from "@expo/vector-icons";
import { useQuery } from "@tanstack/react-query";
import * as Clipboard from "expo-clipboard";
import * as Haptics from "expo-haptics";
import { Image } from "expo-image";
import * as Linking from "expo-linking";
import React, { useState } from "react";
import {
  Alert,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import {
  Bee,
  Bird,
  CrayonUnderline,
  Flower,
  HAND_FONT,
  LABEL_FONT,
  Mushroom,
  PaperBackground,
  PAINT,
  WobbleBox,
  WobbleButton,
} from "@/components/paint";
import { useLocation } from "@/context/LocationContext";
import { fetchNearbySpecies } from "@/services/iNaturalist";
import {
  buildImpactChain,
  getEcosystemRoles,
  getRoleLabel,
} from "@/services/ecologyModel";
import { withCache } from "@/services/cache";

type ReportType = "consumer" | "policy";

const STAKEHOLDERS = [
  {
    id: "city-council",
    name: "City Council",
    role: "Elected Official",
    org: "City Council",
    category: "Government",
    email: "council@yourcity.gov",
    emoji: "🏛️",
    color: PAINT.blue,
    seed: 8,
  },
  {
    id: "parks",
    name: "Parks Dept",
    role: "Director",
    org: "Parks & Recreation",
    category: "Government",
    email: "parks@yourcity.gov",
    emoji: "🌳",
    color: PAINT.grass,
    seed: 12,
  },
  {
    id: "newspaper",
    name: "Local News",
    role: "Environment Reporter",
    org: "Local News",
    category: "Media",
    email: "environment@localnews.com",
    emoji: "📰",
    color: PAINT.orange,
    seed: 16,
  },
  {
    id: "nonprofit",
    name: "Nonprofit",
    role: "Conservation Director",
    org: "Local Conservation Group",
    category: "Nonprofit",
    email: "info@localconservation.org",
    emoji: "❤️",
    color: PAINT.pink,
    seed: 20,
  },
] as const;

function generateReport(
  type: ReportType,
  city: string,
  radius: number,
  speciesName: string,
  scientificName: string,
  role: string,
  observationCount: number,
  chain: ReturnType<typeof buildImpactChain>
): string {
  if (type === "consumer") {
    return `📍 Biodiversity Report — ${city} (${radius}km radius)
Generated by Life Web • ${new Date().toLocaleDateString()}

SPECIES SPOTLIGHT: ${speciesName} (${scientificName})

What we found:
Community scientists have recorded ${observationCount} research-grade observations of ${speciesName} near ${city}. This species plays the role of ${role.toLowerCase()} in the local ecosystem.

Why it matters:
${chain.summary}

What could happen:
${chain.nodes.slice(1).map((n) => `• ${n.description}`).join("\n")}

What you can do:
• Report sightings to iNaturalist
• Support local habitat preservation
• Contact your parks department about habitat management
• Share this report with local conservation groups

Data caveat:
${chain.credibilityNote} All data sourced from iNaturalist community observations.

---
Powered by Life Web & iNaturalist`;
  }

  return `BIODIVERSITY IMPACT ASSESSMENT
${city} Region (${radius}km radius)
Date: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY

Community science observations from iNaturalist indicate notable biodiversity activity near ${city}. This report focuses on ${speciesName} (${scientificName}), documented in ${observationCount} research-grade observations within the study area.

SPECIES PROFILE

Common Name: ${speciesName}
Scientific Name: ${scientificName}
Ecosystem Role: ${role}
Observation Count (Research Grade): ${observationCount}
Study Radius: ${radius}km from ${city}

ECOLOGICAL SIGNIFICANCE

${chain.summary}

POTENTIAL IMPACT CHAIN

${chain.nodes.map((n, i) => `${i + 1}. ${n.label}: ${n.description}`).join("\n")}

DATA METHODOLOGY

All observations sourced from iNaturalist (inaturalist.org) using research-grade quality filter. Data normalized against total observation effort. Seasonal and observer bias are acknowledged limitations.

IMPORTANT CAVEATS

${chain.credibilityNote} Community science data reflects observer effort and accessibility of habitats, not absolute species distribution. This report should be considered alongside formal ecological assessments before policy decisions are made.

RECOMMENDED LOCAL ACTIONS

1. Commission a formal species survey to validate community observations
2. Review habitat management plans for areas with high observation density
3. Engage local naturalist groups in ongoing monitoring
4. Consider wildlife corridor protections where relevant
5. Support citizen science programs that expand observation coverage

DATA SOURCE

iNaturalist (https://www.inaturalist.org)
Powered by Life Web biodiversity app

---
This report was generated using community science data and simplified ecological models. It is intended to inform and educate, not to serve as a definitive scientific or legal document.`;
}

export default function ReportsScreen() {
  const insets = useSafeAreaInsets();
  const { lat, lng, radius, cityName } = useLocation();

  const [reportType, setReportType] = useState<ReportType>("consumer");
  const [generatedReport, setGeneratedReport] = useState<string | null>(null);

  const { data: species, isLoading: speciesLoading } = useQuery({
    queryKey: ["nearby-species", lat, lng, radius],
    queryFn: () =>
      withCache(`nearby-${lat}-${lng}-${radius}`, () =>
        fetchNearbySpecies(lat!, lng!, radius, 50)
      ),
    enabled: !!lat && !!lng,
  });

  const topSpecies = species?.[0];
  const topPhoto =
    topSpecies?.taxon.default_photo?.medium_url ||
    topSpecies?.taxon.default_photo?.square_url;

  function handleGenerate() {
    if (!topSpecies) return;
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    const taxon = topSpecies.taxon;
    const roles = getEcosystemRoles(
      taxon.iconic_taxon_name,
      taxon.preferred_common_name
    );
    const role = getRoleLabel(roles[0]);
    const chain = buildImpactChain(
      taxon.name,
      taxon.iconic_taxon_name,
      taxon.preferred_common_name
    );
    const report = generateReport(
      reportType,
      cityName || "Your Location",
      radius,
      taxon.preferred_common_name || taxon.name,
      taxon.name,
      role,
      topSpecies.count,
      chain
    );
    setGeneratedReport(report);
  }

  async function handleCopy() {
    if (!generatedReport) return;
    await Clipboard.setStringAsync(generatedReport);
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    Alert.alert("Copied!", "Report copied to clipboard.");
  }

  function handleEmail(stakeholder: (typeof STAKEHOLDERS)[number]) {
    if (!generatedReport) {
      Alert.alert(
        "Generate a report first",
        "Tap Generate Report above before sending."
      );
      return;
    }
    const subject = encodeURIComponent(
      `Biodiversity Report — ${cityName || "Local Area"}`
    );
    const body = encodeURIComponent(generatedReport);
    Linking.openURL(
      `mailto:${stakeholder.email}?subject=${subject}&body=${body}`
    );
  }

  const topInsets = insets.top + (Platform.OS === "web" ? 67 : 0);
  const bottomInsets = insets.bottom + (Platform.OS === "web" ? 34 : 0);

  const speciesName =
    topSpecies?.taxon.preferred_common_name || topSpecies?.taxon.name || "—";
  const sciName = topSpecies?.taxon.name || "";

  return (
    <View style={styles.container}>
      <PaperBackground />
      <ScrollView
        contentContainerStyle={[
          styles.scroll,
          {
            paddingTop: topInsets + 18,
            paddingBottom: bottomInsets + 110,
          },
        ]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.title}>Make a Report</Text>
        <CrayonUnderline width={180} color={PAINT.orange} seed={2} />
        <Text style={styles.subtitle}>
          Tell your local leaders what&apos;s happening.
        </Text>

        {/* Type selector */}
        <View style={styles.typeRow}>
          {(["consumer", "policy"] as ReportType[]).map((t, i) => {
            const active = reportType === t;
            return (
              <Pressable
                key={t}
                onPress={() => {
                  setReportType(t);
                  setGeneratedReport(null);
                }}
                style={{ flex: 1 }}
              >
                <WobbleBox
                  width={171}
                  height={46}
                  fill={active ? PAINT.sun : "white"}
                  seed={i + 50}
                  padding={0}
                >
                  <View style={styles.typeInner}>
                    <Text style={styles.typeText}>
                      {t === "consumer" ? "Summary" : "Policy"}
                    </Text>
                  </View>
                </WobbleBox>
              </Pressable>
            );
          })}
        </View>

        {/* Postcard featured species */}
        <View style={styles.postcardWrap}>
          {/* tape */}
          <View style={[styles.tape, styles.tapeLeft]} />
          <View style={[styles.tape, styles.tapeRight]} />

          <View style={styles.postcard}>
            <Text style={styles.postcardKicker}>
              ~ Biodiversity Bulletin ~
            </Text>
            <Text style={styles.postcardTitle} numberOfLines={2}>
              {topSpecies
                ? `The ${speciesName} of ${cityName || "your area"}`
                : "Pick a featured species"}
            </Text>
            <Text style={styles.postcardMeta}>
              📍 {cityName || "Your Location"} · {radius}km · drawn today
            </Text>

            {/* hero strip */}
            <View style={styles.hero}>
              {topPhoto ? (
                <Image
                  source={{ uri: topPhoto }}
                  style={StyleSheet.absoluteFill}
                  contentFit="cover"
                />
              ) : (
                <View style={[StyleSheet.absoluteFill, styles.heroFallback]}>
                  <Bee size={48} />
                  <Flower size={48} petal={PAINT.pink} />
                  <Bird size={48} />
                </View>
              )}
            </View>

            {/* stats */}
            {topSpecies && (
              <View style={styles.statRow}>
                <PostcardStat
                  n={String(topSpecies.count)}
                  l="sightings"
                  c={PAINT.sun}
                  seed={3}
                />
                <PostcardStat
                  n={`${radius}km`}
                  l="radius"
                  c={PAINT.blue}
                  seed={9}
                />
                <PostcardStat
                  n={getRoleLabel(
                    getEcosystemRoles(
                      topSpecies.taxon.iconic_taxon_name,
                      topSpecies.taxon.preferred_common_name
                    )[0]
                  )
                    .split(" ")[0]
                    .toUpperCase()}
                  l="role"
                  c={PAINT.grassDeep}
                  seed={17}
                />
              </View>
            )}

            {/* what we found */}
            {topSpecies && (
              <View style={styles.finding}>
                <Text style={styles.findingTitle}>What we found:</Text>
                <Text style={styles.findingBody}>
                  Community scientists logged{" "}
                  <Text style={styles.highlight}>
                    {topSpecies.count} research-grade sightings
                  </Text>{" "}
                  of {speciesName} (
                  <Text style={styles.findingItalic}>{sciName}</Text>) within
                  {" "}
                  {radius}km of {cityName || "your location"}.
                </Text>
              </View>
            )}

            <Text style={styles.signoff}>
              — drawn from iNaturalist sightings ✏️
            </Text>
          </View>
        </View>

        {/* Generate */}
        <View style={{ alignItems: "center", marginTop: 20 }}>
          <WobbleButton
            label={generatedReport ? "Re-draw Report" : "Generate Report"}
            color={topSpecies ? PAINT.grass : PAINT.paperDeep}
            width={300}
            height={58}
            seed={9}
            onPress={handleGenerate}
            disabled={!topSpecies || speciesLoading}
            textColor={PAINT.ink}
          />
        </View>

        {/* Generated report textbox */}
        {generatedReport && (
          <View style={styles.reportSection}>
            <View style={styles.reportHeader}>
              <Text style={styles.reportLabel}>your report ↓</Text>
              <Pressable onPress={handleCopy}>
                <WobbleBox
                  width={92}
                  height={36}
                  fill={PAINT.cream}
                  seed={71}
                  padding={0}
                >
                  <View style={styles.copyInner}>
                    <Feather name="copy" size={14} color={PAINT.ink} />
                    <Text style={styles.copyText}>copy</Text>
                  </View>
                </WobbleBox>
              </Pressable>
            </View>
            <WobbleBox
              width={358}
              height={Math.min(420, 80 + generatedReport.length * 0.32)}
              fill={PAINT.cream}
              seed={77}
              padding={14}
            >
              <ScrollView
                showsVerticalScrollIndicator={false}
                style={{ flex: 1 }}
                contentContainerStyle={{ paddingBottom: 8 }}
                nestedScrollEnabled
              >
                <Text style={styles.reportText}>{generatedReport}</Text>
              </ScrollView>
            </WobbleBox>
          </View>
        )}

        {/* Send to */}
        <View style={{ marginTop: 28 }}>
          <Text style={styles.sendTitle}>send to →</Text>
          <Text style={styles.sendSub}>
            taps open your email app with a pre-filled draft. you review and
            send.
          </Text>
          <View style={styles.stakeholderGrid}>
            {STAKEHOLDERS.map((s) => (
              <Pressable
                key={s.id}
                onPress={() => handleEmail(s)}
                style={styles.stakeholderCell}
              >
                <WobbleBox
                  width={170}
                  height={70}
                  fill="white"
                  seed={s.seed}
                  padding={0}
                >
                  <View style={styles.stakeholderInner}>
                    <View
                      style={[
                        styles.stakeholderEmojiWrap,
                        { backgroundColor: s.color },
                      ]}
                    >
                      <Text style={styles.stakeholderEmoji}>{s.emoji}</Text>
                    </View>
                    <View style={{ flex: 1 }}>
                      <Text style={styles.stakeholderName} numberOfLines={1}>
                        {s.name}
                      </Text>
                      <Text style={styles.stakeholderRole} numberOfLines={1}>
                        {s.category}
                      </Text>
                    </View>
                  </View>
                </WobbleBox>
              </Pressable>
            ))}
          </View>
          <View style={styles.placeholderNote}>
            <Mushroom size={28} />
            <Text style={styles.placeholderText}>
              Stakeholder contacts are placeholders — replace with your local
              representatives.
            </Text>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}

function PostcardStat({
  n,
  l,
  c,
  seed,
}: {
  n: string;
  l: string;
  c: string;
  seed: number;
}) {
  return (
    <View style={{ flex: 1 }}>
      <WobbleBox width={96} height={60} fill="white" seed={seed} padding={0}>
        <View style={styles.statInner}>
          <Text style={[styles.statNumber, { color: c }]} numberOfLines={1}>
            {n}
          </Text>
          <Text style={styles.statLabel} numberOfLines={1}>
            {l}
          </Text>
        </View>
      </WobbleBox>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: PAINT.paper },
  scroll: { paddingHorizontal: 16 },
  title: {
    fontFamily: HAND_FONT,
    fontSize: 32,
    color: PAINT.ink,
    transform: [{ rotate: "-1deg" }],
    lineHeight: 36,
  },
  subtitle: {
    fontFamily: LABEL_FONT,
    fontSize: 15,
    color: PAINT.inkSoft,
    marginTop: 6,
  },
  typeRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 18,
  },
  typeInner: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  typeText: {
    fontFamily: HAND_FONT,
    fontSize: 22,
    color: PAINT.ink,
  },
  postcardWrap: {
    marginTop: 24,
    alignItems: "center",
  },
  postcard: {
    width: 340,
    backgroundColor: "white",
    borderWidth: 3,
    borderColor: PAINT.ink,
    padding: 16,
    transform: [{ rotate: "-1.5deg" }],
  },
  tape: {
    position: "absolute",
    top: -10,
    width: 60,
    height: 22,
    borderWidth: 1.5,
    borderColor: PAINT.ink,
    zIndex: 2,
  },
  tapeLeft: {
    left: 36,
    backgroundColor: PAINT.sun + "cc",
    transform: [{ rotate: "-9deg" }],
  },
  tapeRight: {
    right: 36,
    backgroundColor: PAINT.pink + "cc",
    transform: [{ rotate: "8deg" }],
  },
  postcardKicker: {
    fontFamily: HAND_FONT,
    fontSize: 14,
    color: PAINT.inkMute,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  postcardTitle: {
    fontFamily: HAND_FONT,
    fontSize: 26,
    color: PAINT.ink,
    marginTop: 4,
    lineHeight: 28,
  },
  postcardMeta: {
    fontFamily: LABEL_FONT,
    fontSize: 12,
    color: PAINT.inkSoft,
    marginTop: 4,
  },
  hero: {
    marginTop: 12,
    height: 130,
    borderWidth: 2.5,
    borderColor: PAINT.ink,
    backgroundColor: PAINT.sun,
    overflow: "hidden",
  },
  heroFallback: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: PAINT.sun,
  },
  statRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  statInner: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  statNumber: {
    fontFamily: HAND_FONT,
    fontSize: 20,
    lineHeight: 22,
  },
  statLabel: {
    fontFamily: LABEL_FONT,
    fontSize: 10,
    color: PAINT.inkSoft,
    marginTop: 2,
  },
  finding: {
    marginTop: 14,
    padding: 10,
    backgroundColor: PAINT.cream,
    borderWidth: 2,
    borderColor: PAINT.ink,
  },
  findingTitle: {
    fontFamily: HAND_FONT,
    fontSize: 18,
    color: PAINT.ink,
  },
  findingBody: {
    fontFamily: LABEL_FONT,
    fontSize: 13,
    color: PAINT.ink,
    marginTop: 4,
    lineHeight: 19,
  },
  findingItalic: { fontStyle: "italic", color: PAINT.inkSoft },
  highlight: {
    backgroundColor: PAINT.sun,
    color: PAINT.ink,
  },
  signoff: {
    marginTop: 12,
    fontFamily: HAND_FONT,
    fontSize: 14,
    color: PAINT.inkMute,
    textAlign: "right",
  },
  reportSection: { marginTop: 22, alignItems: "center" },
  reportHeader: {
    width: 358,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  reportLabel: {
    fontFamily: HAND_FONT,
    fontSize: 22,
    color: PAINT.ink,
  },
  copyInner: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  copyText: {
    fontFamily: HAND_FONT,
    fontSize: 16,
    color: PAINT.ink,
  },
  reportText: {
    fontFamily: LABEL_FONT,
    fontSize: 12,
    color: PAINT.ink,
    lineHeight: 18,
  },
  sendTitle: {
    fontFamily: HAND_FONT,
    fontSize: 24,
    color: PAINT.ink,
    transform: [{ rotate: "-0.5deg" }],
  },
  sendSub: {
    fontFamily: LABEL_FONT,
    fontSize: 13,
    color: PAINT.inkSoft,
    marginTop: 4,
    lineHeight: 18,
  },
  stakeholderGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 12,
    justifyContent: "space-between",
  },
  stakeholderCell: {},
  stakeholderInner: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    gap: 10,
  },
  stakeholderEmojiWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: PAINT.ink,
    alignItems: "center",
    justifyContent: "center",
  },
  stakeholderEmoji: { fontSize: 20 },
  stakeholderName: {
    fontFamily: HAND_FONT,
    fontSize: 18,
    color: PAINT.ink,
    lineHeight: 20,
  },
  stakeholderRole: {
    fontFamily: LABEL_FONT,
    fontSize: 11,
    color: PAINT.inkSoft,
  },
  placeholderNote: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 16,
    padding: 12,
    backgroundColor: PAINT.cream,
    borderWidth: 2,
    borderColor: PAINT.ink,
    borderStyle: "dashed",
  },
  placeholderText: {
    flex: 1,
    fontFamily: LABEL_FONT,
    fontSize: 12,
    color: PAINT.inkSoft,
    lineHeight: 17,
  },
});
